Person.create(name: 'Daenerys Targaryen', title: 'Queen of Meereen and Mother of Dragons', quote: 'I will take what is mine with blood and fire.', image: 'http://i.imgur.com/DjHJq4E.jpg', age: 18)
Person.create(name: 'Jon Snow', title: 'Lord Commander of the Nights Watch', quote: '"Night gathers, and now my watch begins."', image: 'http://i.imgur.com/WadV6VI.jpg', age: 19)
Person.create(name: 'Tyrion Lannister', title: 'Hand of the King and Master of Coin', quote: 'A Lannister always pays his debts.', image: 'http://i.imgur.com/rNHNWca.jpg', age: 35)
Person.create(name: 'Tywin Lannister', title: 'Wormchow', quote: '"You cannot eat love, nor buy a horse with it, nor warm your halls on a cold night."', image: 'http://i.imgur.com/ovtHd1H.jpg', age: 60)
Person.create(name: 'Arya Stark', title: 'Princess of Winterfell', quote: '...anyone can be killed.', image: 'http://i.imgur.com/Csq9exg.jpg', age: 14)
Person.create(name: 'Cersei Lannister', title: 'King Mother and Lady of Casterly Rock', quote: '"The gods have no mercy, that’s why they’re gods."', image: 'http://i.imgur.com/jYeeCJ3.jpg', age: 40)
Person.create(name: 'Robb Stark', title: 'Deceased', quote: 'It was the only honorable thing to do.', image: 'http://i.imgur.com/uYC3zzt.jpg', age: 21)


House.create(name: 'House Baratheon', motto: 'Ours is the fury.', sigil: 'http://i.imgur.com/iJtBKIR.png')
House.create(name: 'House Bolton', motto: 'Our blades are sharp.', sigil: 'http://i.imgur.com/uPoc9Jh.jpg')
House.create(name: 'House Lannister', motto: 'Hear me roar!', sigil: 'http://i.imgur.com/gOwmzoU.jpg')
House.create(name: 'House Martell', motto: '"Unbowed, Unbent, Unbroken."', sigil: 'http://i.imgur.com/XaIiVNI.jpg')
House.create(name: 'House Stark', motto: 'Winter is coming.', sigil: 'http://i.imgur.com/zpVjXsa.jpg')
House.create(name: 'House Targaryen', motto: 'Blood and fire.', sigil: 'http://i.imgur.com/4FuSpZt.jpg')
